CREATE TABLE dbo.Users (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE dbo.Profiles (
    UserId UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Bio NVARCHAR(500) NULL,
    Gender NVARCHAR(50) NULL,
    Preference NVARCHAR(50) NULL,
    CONSTRAINT FK_Profiles_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
);

CREATE TABLE dbo.Sessions (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    TokenHash NVARCHAR(255) NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Sessions_Users FOREIGN KEY (UserId) REFERENCES dbo.Users(Id)
);

CREATE INDEX IX_Sessions_UserId ON dbo.Sessions(UserId);
CREATE INDEX IX_Sessions_ExpiresAt ON dbo.Sessions(ExpiresAt);